CC=g++

all: test1 test2 test3 test4
.PHONY:all clean


test1:test1.cpp
	$(CC) -std=gnu++11  test1.cpp -o test1
test2:test2.cpp
	$(CC) -std=gnu++11  test2.cpp -o test2
test3:test3.cpp
	$(CC) -std=gnu++11  test3.cpp -o test3
test4:test4.cpp
	$(CC) -std=gnu++11  test4.cpp -o test4
clean:
	rm test1 test2 test3 test4
