CC=g++

all: test1 test2 test3 test4 test5 test6 test7 test8
.PHONY:all clean


test1:test1.cpp
	$(CC) -std=gnu++11  test1.cpp -o test1
test2:test2.cpp
	$(CC) -std=gnu++11  test2.cpp -o test2
test3:test3.cpp
	$(CC) -std=gnu++11  test3.cpp -o test3
test4:test4.cpp
	$(CC) -std=gnu++11  test4.cpp -o test4
test5:test5.cpp
	$(CC) -std=gnu++11  test5.cpp -o test5
test6:test6.cpp
	$(CC) -std=gnu++11  test6.cpp -o test6
test7:test7.cpp
	$(CC) -std=gnu++11  test7.cpp -o test7
test8:test8.cpp
	$(CC) -std=gnu++11  test8.cpp -o test8
clean:
	rm test1 test2 test3 test4 test5 test6 test7 test8
