CC=g++

all: test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 recursive queen newoop stackoop
.PHONY:all clean


stackoop:stackoop.cpp
	$(CC) -std=gnu++11  stackoop.cpp -o stackoop
newoop:newoop.cpp
	$(CC) -std=gnu++11  newoop.cpp -o newoop
test1:test1.cpp
	$(CC) -std=gnu++11  test1.cpp -o test1
test2:test2.cpp
	$(CC) -std=gnu++11  test2.cpp -o test2
test3:test3.cpp
	$(CC) -std=gnu++11  test3.cpp -o test3
test4:test4.cpp
	$(CC) -std=gnu++11  test4.cpp -o test4
test5:test5.cpp
	$(CC) -std=gnu++11  test5.cpp -o test5
test6:test6.cpp
	$(CC) -std=gnu++11  test6.cpp -o test6
test7:test7.cpp
	$(CC) -std=gnu++11  test7.cpp -o test7
test8:test8.cpp
	$(CC) -std=gnu++11  test8.cpp -o test8
test9:test9.cpp
	$(CC) -std=gnu++11  test9.cpp -o test9
test10:test10.cpp
	$(CC) -std=gnu++11 test10.cpp -o test10
recursive:recursive.cpp
	$(CC) -std=gnu++11 recursive.cpp -o recursive
queen:queen.cpp
	$(CC) -std=gnu++11 queen.cpp -o queen
clean:
	rm test1 test2 test3 test4 test5 test6 test7 test8 test9 test10 recursive
