CC=g++
CFLAGS=-std=c++11

.PHONE:clean all
all:hello  detar deposit autotest autotest2 innercode largestFactor countchar

largestFactor:largestFactor.cpp
	$(CC) $< $(CFLAGS) -o $@
clean:
	rm hello  detar deposit autotest autotest2 innercode largestFactor
