CCd=g++

all:declarations_in_conditions  
.PHONE:clean all

declarations_in_conditions:declarations_in_conditions.cpp 
	$(CCd) declarations_in_conditions.cpp -o declarations_in_conditions

clean:
	rm declarations_in_conditions 
