CC=g++
CFLAGS=-std=c++11

.PHONE:clean all
all:array find bifind  selectsort bubblesort multimatrix magic equation str statistic

array:array.cpp
	$(CC) $< $(CFLAGS) -o $@

find:find.cpp
	$(CC) $< $(CFLAGS) -o $@
bifind:find.cpp
	$(CC) $< $(CFLAGS) -o $@
selectsort:selectsort.cpp
	$(CC) $< $(CFLAGS) -o $@
bubblesort:bubblesort.cpp
	$(CC) $< $(CFLAGS) -o $@
multimatrix:multimatrix.cpp
	$(CC) $< $(CFLAGS) -o $@
magic:magic.cpp
	$(CC) $< $(CFLAGS) -o $@
equation:equation.cpp
	$(CC) $< $(CFLAGS) -o $@
str:str.cpp
	$(CC) $< $(CFLAGS) -o $@
statistic:statistic.cpp
	$(CC) $< $(CFLAGS) -o $@
clean:
	rm array
