CC=gcc

all: strtoint  macro quicksort
.PHONY:all clean


strtoint:strtoint.c
	$(CC) -std=c99 $< -o $@
macro:macro.c
	$(CC) -std=c99 $< -o $@
quicksort:quicksort.c
	$(CC) -std=c99 $< -o $@
clean:
	rm strtoint 
